### ISSUE TITLE
Purchases broken

### ISSUE THREAD

**Issue by ikoN420** [aStonedPenguin/pLogs-v2-Extra-log-hooks#1]
It seems the Purchases tab is coming up empty. When someone purchases the follow error comes up in console:

[ERROR] addons/p_logs_v2.0.6/lua/plogs/core_sv.lua:67: attempt to get length of a nil value
1. Log - addons/p_logs_v2.0.6/lua/plogs/core_sv.lua:67
2. PlayerLog - addons/p_logs_v2.0.6/lua/plogs/core_sv.lua:86
3. fn - addons/p_logs_v2.0.6/lua/plogs_hooks/darkrp-purchase.lua:4
4. Call - addons/ulib/lua/ulib/shared/hook.lua:105
5. callback - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:596
6. unknown - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:156
7. unknown - lua/includes/modules/concommand.lua:54

**Comment by aStonedPenguin** [comment]
yep, made a small typo
